
# docker-compose.web.yml
version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: "http://localhost:4242"
    container_name: abrs-web
    ports:
      - "8080:80"
    restart: unless-stopped
