name: release
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - id: meta
        run: |
          echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "date=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VITE_BACKEND_URL=/api
          tags: |
            ghcr.io/fredinard/abrasia-frontend:latest
            ghcr.io/fredinard/abrasia-frontend:${{ steps.meta.outputs.date }}-${{ steps.meta.outputs.sha }}
          provenance: false
          sbom: false
